### ISSUE TITLE
Warning not given if untracked files are present

### ISSUE THREAD

**Issue by LouiseABowler** [alan-turing-institute/repro-catalogue#44] opened 2020-04-30 17:31 UTC
Running `catalogue engage --input_data data/ --code .` with uncommitted changes to a file results in the expected warning:
```
Working directory contains uncommitted changes.
Do you want to stage and commit all changes? (y/[n])
```
but the warning is not generated if there are only untracked files present.

Is this expected behaviour? It's not what I would personally expect, as someone developing their analysis could have added new functionality in the untracked files.

**Comment by radka-j** [comment] 2020-05-01 07:37
Good spot! On the other hand, it is possible someone has files around that they do not want to commit. So maybe we just want to give a warning in that instances - the user has to indicate they do not want to commit these files?

Note: the `git.Repo` object has the `untracked_files` property that can be used for this.

**Comment by LouiseABowler** [comment] 2020-05-01 09:23
Another warning would be fine here I think - as long as it nudges the user into thinking about the current state of their repo before running their analysis.

Alternatively, we could expect the user to add the names of the files to their `.gitignore` if they genuinely don't want them added to the repo, and then re-use the original warning that prevents the engage process from continuing.

**Comment by radka-j** [comment] 2020-05-01 10:47
@edaub do you have any thoughts on what the appropriate behaviour should be?

**Comment by edaub** [comment] 2020-05-01 15:05
I agree that checking this makes sense. As for what is the "correct" behavior (quiet warning, warning that requires a response, or error), I don't know and think a case could be made for any of them.

I personally don't mind keeping untracked, unignored files hanging around in my local copy of the repository, and I would argue that I _shouldn't_ add them to `.gitignore` because they only really apply to me and thus don't belong in the shared remote. But I think one could argue that this isn't necessarily the best practice.

**Comment by radka-j** [comment] 2020-05-01 15:22
I like the option of a quiet warning or a warning that requires the user to indicate they are happy to proceed. 

I admit that this is motivated by my personal bias. What Eric describes captures how I tend to work as well.

**Comment by radka-j** [comment] 2020-05-06 15:00
The conclusion of the discussion today is that untracked files should be treated the same as uncommitted files. 

Expected behaviour: at `engage` the tool checks whether there are any untracked files and will not proceed until they are committed/removed.

Question: after `disengage` (depending on the directory structure and where the tool is run from) , it is possible that one will end up with new untracked `catalogue_results` and analysis results files. Should this be allowed? What should the behaviour be in this instance?

**Comment by LouiseABowler** [comment] 2020-05-06 17:27
Could (/should) we request that the user adds a couple of folders to their `.gitignore` file? I'd assume those files shouldn't be tracked at all as they aren't part of the codebase.

**Comment by radka-j** [comment] 2020-05-07 15:50
We could set it up so that `catalogue_results/` files can be untracked. I think I prefer this option to asking the users to do extra work by adding this to their `.gitignore`. What do you think?

**Comment by radka-j** [comment] 2020-05-11 11:08
Below is a summary of my understanding of what the expected behaviour of `catalogue` with regards to untracked files should be:
- `catalogue` won't engage/disengage if there are any untracked files (it will output a message to the user similar to what happens if there are uncommitted files)
- `catalogue` will automatically ignore any files generated by `catalogue` (anything in the `catalogue_results` directory) so that the user does not need to add this to their `.gitignore` file

@LouiseABowler @edaub Do you agree with this? Did I miss anything?

**Comment by edaub** [comment] 2020-05-11 12:28
> * `catalogue` won't engage/disengage if there are any untracked files (it will output a message to the user similar to what happens if there are uncommitted files)

I think this is correct. Certainly, if untracked files are not allowed then engaging with them present should be flagged. If the same is true for when running disengage, then we are saying that the analysis can't create any new files that aren't already ignored (in the event that the lower level directory is the git repository). I think this is reasonable behavior, but I think the documentation should probably make it abundantly clear (like in its own section at the beginning) that (1) we are making several assumptions about how the analysis is conducted, (2) breaking those assumptions won't let you use the tool, and (3) this is done to enourage good practices for reproducing your work.

**Comment by radka-j** [comment] 2020-05-11 12:37
I like the idea of making this very clear in the documentation. We could expand the pre-requisites section of the README and add the points made above there (at the moment it mentions code having to be in a git repo). It could also explain that one has two workflow options: 1) analysis script creates results files outside the git repo or 2) the results files are added to a `.gitignore` file (with an example of what this might look like).

**Closed as completed** 2020-05-14 12:50 UTC
